---
name: "Linter Workflow"
run-name: Linter check for ${{ github.sha }}
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: false

jobs:
  tg-plan:
    name: "Run Super-Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
        id: checkout
      - name: Super-Linter
        id: super-linter
        uses: super-linter/super-linter@v8.3.2
